import test from 'node:test';import assert from 'node:assert/strict';
import {minimumPoints,replay,emptyHigh,activeEvents,undoTarget,validateImport} from '../rules.js';
let n=0;const event=(type,rest={})=>({id:String(++n),timestamp:n,type,...rest});
const chance=(chars=['mumei'],kind='single',high=emptyHigh(),lit={mumei:false})=>event('chance',{characters:chars,chanceType:kind,high,illuminated:lit});
test('single dark, unconfirmed flash, CZ flash and confirmed non-CZ flash lower bounds',()=>{const a=chance();assert.deepEqual(minimumPoints(a),{mumei:1});a.illuminated.mumei=true;assert.equal(minimumPoints(a).mumei,1);assert.equal(minimumPoints(a,{[a.id]:'cz-or-unknown'}).mumei,1);assert.equal(minimumPoints(a,{[a.id]:'no-cz'}).mumei,15);});
test('high single regardless of illumination',()=>{for(const lit of [true,false,null])assert.equal(minimumPoints(chance(['mumei'],'single',{...emptyHigh(),mumei:true},{mumei:lit})).mumei,15);});
test('mixed high double independently awards 30 and 15',()=>assert.deepEqual(minimumPoints(chance(['mumei','ikoma'],'double',{...emptyHigh(),mumei:true},{mumei:null,ikoma:false})),{mumei:30,ikoma:15}));
test('allstar records biba unknown without fabricating points or auto reset',()=>{const a=chance(['mumei','ikoma','biba'],'allstar',{...emptyHigh(),biba:true},{mumei:null,ikoma:null,biba:null});assert.deepEqual(minimumPoints(a),{mumei:30,ikoma:30,biba:null});assert.equal(replay([a]).cz.length,0);assert.equal(replay([a]).current.biba.unknownAmounts,1);});
test('CZ saves only target, ST archives/reset high and all targets; cumulative retained',()=>{const es=[chance(),chance(['ikoma'],'single',emptyHigh(),{ikoma:false}),event('cz',{character:'mumei'}),event('state',{character:'biba',enabled:true}),event('st')];const r=replay(es);assert.equal(r.cz[0].stats.points,1);assert.equal(r.sessions[0].current.ikoma.points,1);assert.equal(r.current.ikoma.points,0);assert.equal(r.total.ikoma.points,1);assert.deepEqual(r.high,emptyHigh());});
test('normal illumination denominator excludes high, compound and unknown',()=>{const es=[chance(['mumei'],'single',emptyHigh(),{mumei:true}),chance(['mumei'],'single',{...emptyHigh(),mumei:true},{mumei:false}),chance(['mumei','ikoma'],'double',emptyHigh(),{mumei:null,ikoma:null})];const r=replay(es);assert.equal(r.total.mumei.normal,1);assert.equal(r.total.mumei.normalFlash,1);assert.equal(r.total.mumei.chances,3);assert.equal(r.total.mumei.unknown,1);});
test('retroactive resolve recomputes archived CZ; undo resolve restores pending',()=>{const a=chance(['mumei'],'single',emptyHigh(),{mumei:true}),cz=event('cz',{character:'mumei'}),res=event('resolve',{target:a.id,result:'no-cz'}),es=[a,cz,res];assert.equal(replay(es).cz[0].stats.points,15);es.push(event('undo',{target:res.id}));assert.equal(replay(activeEvents(es)).cz[0].stats.points,1);assert.equal(undoTarget(es),cz.id);es.push(event('undo',{target:cz.id}));assert.equal(replay(activeEvents(es)).current.mumei.points,1);});
test('serialization roundtrip preserves independent high snapshots and all audit events',()=>{const es=[event('state',{character:'mumei',enabled:true}),chance(['mumei'],'single',{...emptyHigh(),mumei:true},{mumei:false})];const data={schemaVersion:1,machine:'S-KABANERI-2022',sessions:[{id:'session',startedAt:1,events:es}]};assert.deepEqual(validateImport(JSON.parse(JSON.stringify(data))),data);assert.throws(()=>validateImport({schemaVersion:1,machine:'S-KABANERI-2022',sessions:[{id:'s',startedAt:1,events:[chance(['unknown'])]}]}));});

test('allstar high affects only named characters; unknown is not zero actual reduction',()=>{const a=chance(['mumei','ikoma','biba'],'allstar',{...emptyHigh(),mumei:true},{mumei:null,ikoma:null,biba:null});assert.deepEqual(minimumPoints(a),{mumei:60,ikoma:30,biba:null});});
test('imports reject unsafe ids, dangling references and different machines',()=>{const make=events=>({schemaVersion:1,machine:'S-KABANERI-2022',sessions:[{id:'s',startedAt:1,events}]});assert.throws(()=>validateImport(make([event('undo',{target:'missing'})])));assert.throws(()=>validateImport(make([{...chance(),id:'<script>'}])));assert.throws(()=>validateImport({...make([]),machine:'UNATO'}));});
